name: Revisi칩n autom치tica de documentaci칩n Markdown

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Nombre de usuario o de organizaci칩n de GitHub"
        required: true
        default: "area73"

jobs:
  auto-doc-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Setup Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run Markdown reviewer
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TARGET_GITHUB_ACCOUNT: ${{ github.event.inputs.target }}
        run: node index.js
